### ISSUE TITLE
Full pool names don't always fit image title

### ISSUE THREAD

**Issue by rphair** [cexplorer/cexplorer.io#10]
Our pool name **Centre for Open Systems Deployment**, especially its last long word **Deployment**, does not fit as a title for the graphical epoch summary distributed through the Cexplorer bot:

![COSD banner, last word Deployment truncated](https://user-images.githubusercontent.com/2572798/187582511-3100ec89-2fba-4c6c-9dff-152b2f1c7b6e.jpg)

**To reproduce**: subscribe to our pool with the Cexplorer bot, select "Epoch Summary" (?) notifications, and wait to see an image like this in the Telegram bot message.  This may also appear in other sharing contexts... the web site is down at this moment so we can't check.

**Expected behaviour**: layout should probably compress font size on top line, so additional lines don't push the rest of the graphics down.

**Additional context** Newman & I (@COSDpool) had a dialogue by Telegram PM in January 2021 that discussed various ways of proportionally fitting text to fix a prior AdaPools layout problem.

**Comment by rphair** [comment]
p.s. web site back up now: as suspected, we have a problem with the corresponding pool banner on the Share page, which uses the same text spacing for the graphical title (i.e. the last word of our pool name "Deployment" is also omitted):
https://js.cexplorer.io/img/p-b-1/pool1e98xlcgj80c3rdmm27v5hnvrdtut52e65uk0ema7ctfag596vr2.jpg

![pool1e98xlcgj80c3rdmm27v5hnvrdtut52e65uk0ema7ctfag596vr2](https://user-images.githubusercontent.com/2572798/187588098-21658419-5cfc-4c63-9745-6faf181c4f66.jpg)

Also we can see here the pool subtitle, which in our case contains `&amp;` to display as valid HTML in most contexts, is not interpreted correctly as `&` as it would be on Daedalus & other pool listings.  **Expected Behaviour**: for `*&amp;` to map to `&` before any text processing. 🙏

**Comment by cexplorer** [comment]
Thank you @rphair.

Fixes should be on the way and changes applied very soon :)

**Comment by rphair** [comment]
thanks; I can confirm both the Telegram delivered image and the downloadable banner have our pool title fit properly to the margin 🤓
