### ISSUE TITLE
Pool Doesn't show when searched, logo doesn't upload with write-in meta

### ISSUE THREAD

**Issue by CardanoKnoXProtocol** [cexplorer/cexplorer.io#13]
My pool ticker is KnoX. I've enable extended metadata and signed pool.cert to allow for updated hash. 

Knoxprotocol.com/poolMetaData.json
knoxprotocol.com/extendedmeta.json

As of today, I'm unable to see my pool on cexplorer.io unless i go to the SPO page where I manage it. I have thus far been unsuccessful at getting cexplorer to cache my extended meta file and therefore have tried the write in method. In either case, my stake pool is no longer displaying in search for some reason. This is a new issue as of a few hours ago. 

Can someone help? My email is will@liftedholdings.com

Updated information:
The pool seems to have no issue on CardanoScan. I was able to successfully view and claim it this morning.

However, when I view my Yuori wallet, it shows that my pledge is deligated to DIGI (The pool I was deligated to prior to starting my own pool). I am unable to search for KNOX or see that my wallet is delegated to it within Yuori. I'll check ADAlite soon and update you. 

Further Update:
My developers say it's unrelated. But I did recently transfer TWO adahandles into one of the owner wallet accounts. I do notice some confusion in the back end regarding those wallets holding two separate ADA Handles. It could be completely unrelated but I wanted to share in case it may have caused the issue. The timing was close between the two events.

**Comment by CardanoKnoXProtocol** [comment]
Any update guys?

**Comment by cexplorer** [comment]
we have an idea where the issue is, please let's wait until epochs transition and see what's next. thanks for your patience and sorry.

**Comment by CardanoKnoXProtocol** [comment]
Thank you for your comment. The Epoch has transitioned. My ticker photo is now showing. But the pool is still not visible on Yurori or on Cexplorer.io (Unless viewed in new pools, or the owner console). It seems to think the pledge is not met and is not showing the other two pledge wallet addresses. Looking forward to advertising my pool, but I don't want to do so until i become visible on your site and in Yurori Again. 

Thanks!

**Comment by cexplorer** [comment]
Thank you for patience. Please check it now, its look like all okay now.

(Backend needs  +hour after epoch transition to settle dust as DB is really huge and some ops needed some time to calculations)
