### ISSUE TITLE
Pool operator rewards missing for one epoch

### ISSUE THREAD

**Issue by MarcelKlammer** [cexplorer/cexplorer.io#14]
Pool operator rewards from e347 missing here:
https://cexplorer.io/pool/pool16u5trhs7ysdh2e8aadk0p8xp52sczl8s29ay6ythv3sxujmdfeu/rewards#data

While it's correct here:
https://adapools.org/pool/d728b1de1e241b7564fdeb6cf09cc1a2a1817cf0517a4d117764606e

**Comment by cexplorer** [comment]
Thank you Marcel. Please close this issue if is it okay :)

Fixed and measures have been taken to prevent it from happening again.
