### ISSUE TITLE
New BOT and cexplorer.io shows boggus POOL information.

### ISSUE THREAD

**Issue by mkungla** [cexplorer/cexplorer.io#15]
**Describe the bug**
cexplorer.io shows random numbers for some pools.

| adapools.org | cexplorer.io |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/15878458/189054758-2684dd5e-76a6-4caf-abf6-ff457238e4fb.png) | ![image](https://user-images.githubusercontent.com/15878458/189054892-0a647600-606b-4c76-b0c2-fc41a7bf12fe.png) |

this e.g. is from my pool which has not even made a blocks yet.
https://cexplorer.io/pool/pool1a8h7s4q2674s5aaqkp5dg598qh097s4krjwggdxx0pwgcl2c5cm

**Comment by cexplorer** [comment]
Fixed, thank you. Fixed and measures have been taken to prevent it from happening again (hope)
