### ISSUE TITLE
Mistyping error on Wiki - Epochs

### ISSUE THREAD

**Issue by OdairTrujillo** [cexplorer/cexplorer.io#16]
**Describe the bug**
It is just a mistyping error, I think. The original text comes like this:

> Someone has just delegated their coins for the first time, another user's skaje has just been used by the pool in that epoch, older users are getting rewards.

**To Reproduce**
1. Go to https://cexplorer.io/wiki/epochs-in-cardano 
2. Read the fourth paragraph

**Expected behavior**
Te text sould be like this:

> Someone has just delegated their coins for the first time, another user's stake has just been used by the pool in that epoch, older users are getting rewards.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
Just fix the mistyping error.

**Comment by cexplorer** [comment]
Thank you, fixed :)
