### ISSUE TITLE
No notifications / cannot add pool

### ISSUE THREAD

**Issue by cryptophonic** [cexplorer/cexplorer.io#17]
**Describe the bug**
When adding a pool, it never shows up under Active Notifications.  In the console: Uncaught TypeError: Cannot read properties of undefined (reading 'top')

**To Reproduce**
1.  click on the telegram url https://cexplorer.io/telegram?id=xyz&
2.  type a pool id in "Add pool to watchlist"
3.  nothing happens

**Expected behavior**
Expected pools to be added and notifications turned on.

![image](https://user-images.githubusercontent.com/409166/189492132-ffdaa542-8cfb-421d-acca-1a1d203e3726.png)

**Desktop (please complete the following information):**
Chome browser on Linux

**Comment by cexplorer** [comment]
Which pool ID are you adding please?

Have you less than 100 pools in monitoring? (this is max-limit actually)

Thanks.

**Comment by mark-microtick** [comment]
I am trying to add sunny pool id. I have no pool ids because no matter
which one I try it fails.

**Comment by cexplorer** [comment]
Hmmm, weird, its working on all tested devices (FF, Brave, Chrome, Safari). Cannot reproduce this issue :(

**Comment by mark-microtick** [comment]
Must be my account.  I'll have to find something else to use.
