### ISSUE TITLE
Query for pool yields no results

### ISSUE THREAD

**Issue by Jack-0** [cexplorer/cexplorer.io#18]
**To Reproduce**
1. enter 9000 into the search bar 
2. navigates to https://cexplorer.io/search?query=9000
3. No results

**Expected behavior**
Expect to see stake pool with ticker 9000 (https://cexplorer.io/pool/pool1fu6ppur5uumrpydpeswzrvfg4epr68xw39aar9rcu56tk5ukat3)

**Additional context / Considerations**
- Does the back-end do something odd with integer based pool names? Just a though but probably not as 000 and 00000 yield results.
- Updated the pools metadata a couple weeks back (including ticker change) . But these changes should now be reflected. Is the DB source invalid or infrequent checks (...or never updated once a ticker is found)?

Thanks, Jack

**Comment by cexplorer** [comment]
Thank you @Jack-0. Fixed.
