### ISSUE TITLE
Tool tip has a potential spelling error

### ISSUE THREAD

**Issue by ubani** [cexplorer/cexplorer.io#19]
**Describe the bug**

There seems to be a typo in the tool tip when hovering over the Twitter symbol.
In the tool tip `Twitter` is spelled `Twittttter`.
Please see attached screenshot.

**Screenshots**

<img width="410" alt="screenshot-2022-10-06_09 56 53" src="https://user-images.githubusercontent.com/7843228/194406942-97f34a3f-14c8-4c51-9510-898bbf9f6c27.png">

**Desktop**
 - OS: Mac Monterey
 - Browser Safari
 - Version 15.6.1

**Comment by cexplorer** [comment]
it was once meant as a joke, but not everyone gets it, so we'll fix it, thanks.
