### ISSUE TITLE
Foreign account address Indicator means?

### ISSUE THREAD

**Issue by Kartiiyer12** [cexplorer/cexplorer.io#20]
For the transactions in cexplorer, some of the output addresses are indicated as "Foreign account". What does that mean? Does it mean the output address is not part of the same cardano-wallet and an external address? Can someone clarify. 
<img width="1138" alt="Screenshot 2022-10-10 at 12 58 58" src="https://user-images.githubusercontent.com/106822766/194861453-0d2ee30a-927a-4c9e-b940-95179835c7b8.png">

**Comment by cexplorer** [comment]
Exactly. 

Foreign account is different from sender and not contain sender´s stake key.

**Comment by Kartiiyer12** [comment]
Hi cexplorer, Thank you for the response. How do you determine that for Byron addresses as they do not contain the stake keys?

**Comment by cexplorer** [comment]
aha, I see. can you send the address in text format / url to this page? let's see, it's a bit confused here I agree and thank you.

**Comment by Kartiiyer12** [comment]
The address for the transcaction is DdzFFzCqrhsmzGAErJQDqRzJD6SjDJ8PD3i3a1VeSYVmWizNJkfnAcqKqVSyDPDf2xQ33a1mbMGMhaQKRrDMoQuoT8R88KzFrZG5ghnx

Both the transactions are confusing - 
https://cexplorer.io/address/DdzFFzCqrhsmzGAErJQDqRzJD6SjDJ8PD3i3a1VeSYVmWizNJkfnAcqKqVSyDPDf2xQ33a1mbMGMhaQKRrDMoQuoT8R88KzFrZG5ghnx/tx#data


But when we click on the transaction details, it shows differently which seems right.
https://cexplorer.io/tx/2fcfb3e60fb8c1f102711e48480e47f8b4b8acad6c2fc93f29eb6460ffc0da0a

https://cexplorer.io/tx/55438350ca4fcdba76127cbd45f0b1915ef278f1272dd29b93d0bbfedf8c6fc7

**Comment by Kartiiyer12** [comment]
So in the First link for Byron addresses, how are you determining the output address is an "foreign account" and not from same wallet?
