### ISSUE TITLE
Some Pool Summary JSON Metadata is Incorrect

### ISSUE THREAD

**Issue by lordb-rocks** [cexplorer/cexplorer.io#21]
**Describe the bug**
Some data I pull from js.adapools.org/pools/<pool_id>/summary.json is wrong. I use this data to drive my Grafana panel.

**To Reproduce**
1. Go to [js.adapools.org/pools/<pool_id>/summary.json](https://js.adapools.org/pools/c95617e76c620b0c55b02deb3bbac70067a3e8a074fb05008ee17215/summary.json)
2. **pledged** shows '0' when there is 239.4k in my pool's wallet w/200k pledge (displays correctly on my pool's cexplorer.io page)
3. **delegators** shows '21' while cexplorer.io page displays 57
4. **blocks_epoch** shows '0' while cexplorer.io blocks page displays 1 for epoch #368
5. **blocks_lifetime** shows '318' while cexplorer.io displays 319

**Expected behavior**
It is expected that the json data reflect the same correct data displayed on my pool's cexplorer.io page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 & macOS Mojave
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
The json data was correct up until 1.35.3 Vasil updates went live

**Comment by cexplorer** [comment]
it is correct as we announced two months ago js.adapools is deprecated :)

take a look there please: https://cexplorer.io/devs

**Comment by lordb-rocks** [comment]
Ah! I missed the announcement. So I can switch over to [https://js.cexplorer.io/api-static/pool/%poolIdBech%.json](https://js.cexplorer.io/api-static/pool/%poolIdBech%.json) ? I don't use any of the data for public display, just my own personal dashboard.

**Comment by cexplorer** [comment]
Yeah, switch to new outputs please (you need a small modification in your script as some fields are different).

**Comment by lordb-rocks** [comment]
Thanks for the info. Already made the changes. Works great 👍🏻
