### ISSUE TITLE
FR: Invalid Staking Status/ Rewards for ScriptHash addresses

### ISSUE THREAD

**Issue by will991** [cexplorer/cexplorer.io#22]
**Describe the bug**
I have an addresses of [type 3](https://cips.cardano.org/cips/cip19/#shelleyaddresses) - meaning I am using two different Plutus Scripts, one for the spending and another one for staking.

**To Reproduce**
1. Go to [Address](https://preview.cexplorer.io/address/addr_test1xrv0allwae07q7g92uvjsrf2jcpaj0wp9zwzmluezgmc65wqyndkwqtt79qjd5h6wmrrac5rcl6q6lt7fh4t7g665d2q7xadxs)
2. Check **Staking Section** or **Rewards Tab**
3. Nothing - even though there was stake in the past that earned rewards.

**Expected behavior**
Expected rewards history or stake status active. Rewards have been earned for this address in the past.

**Comment by cexplorer** [comment]
Thank you, noted :)
