### ISSUE TITLE
Website blocked by Cisco Umbrella

### ISSUE THREAD

**Issue by brouwerQ** [cexplorer/cexplorer.io#23]
I don't know if there's something you can do about this, but your website is flagged as a security thread by the Cisco Umbrella firewall.

![image](https://user-images.githubusercontent.com/25958442/196632469-55316cf6-758b-42c1-a12e-053749de0051.png)

**Comment by cexplorer** [comment]
We have contacted them, thanks for head up. Will update this thread when we have some solution from them.

**Comment by cexplorer** [comment]
@brouwerQ should be fixed now. Please take a look (and if is), close this issue. THank you

**Comment by brouwerQ** [comment]
![image](https://user-images.githubusercontent.com/25958442/198958937-6931a95a-811d-40f5-b916-0ab5330cd862.png)
