### ISSUE TITLE
Pool performance is only calculated from Epoch 371

### ISSUE THREAD

**Issue by PfizerVaccine** [cexplorer/cexplorer.io#25]
Pool performance is only calculated from Epoch 371 on the graph.
Data before that is not displayed as expected.

Example:
https://cexplorer.io/pool/pool16fyda57p3c8gp5r6gmcq5tvqsp6mnzwvkxswgznkuh8wztrp6vv

**Comment by cexplorer** [comment]
Should be fixed.
