### ISSUE TITLE
minted blocks not reported on preprod network

### ISSUE THREAD

**Issue by monkey-jsun** [cexplorer/cexplorer.io#30]
**Describe the bug**
I have set up a staking pool, NSPPP.  My producer nodes are producing blocks as normal, and are reported by logs and gLiveview script.. However those blocks are not shown up in your website.

More info about my pool:

stake pool id : bd70560a29a8f765aaf8a10efb2ea3a7f1d903dabe57cf4b8a2ff24f, or pool1h4c9vz3f4rmkt2hc5y80kt4r5lcajq76hetu7ju29ley7acvclp
URL: https://preprod.cexplorer.io/pool/pool1h4c9vz3f4rmkt2hc5y80kt4r5lcajq76hetu7ju29ley7acvclp
ticker : NSPPP
gLiveview screenshot:

```
        > Cardano Node - (Core - PreProd) : 1.35.3 [950c4e22] < 
┌────────────────────────────────┬────────────┬────────────────────────┐
│ Uptime: 10:57:52               │ Port: 3001 │ Guild LiveView v1.27.3 │
│--------------------------------└────────────┴────────────────────────┤
│ Epoch 34 [94.3%], 06:51:42 remaining                                 │
│ ▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▖▖▖▖▖ │
│                                                                      │
│ Block      : 309219    Tip (ref)  : 13453698  Forks      : 25        │
│ Slot       : 13453692  Tip (diff) : 6 :)      Total Tx   : 0         │
│ Slot epoch : 407292    Density    : 4.822     Pending Tx : 0/0K      │
│- CONNECTIONS --------------------------------------------------------│
│ P2P        : enabled   Cold Peers : 0         Uni-Dir    : 0         │
│ Incoming   : 1         Warm Peers : 0         Bi-Dir     : 1         │
│ Outgoing   : 1         Hot Peers  : 1         Duplex     : 1         │
│- BLOCK PROPAGATION --------------------------------------------------│
│ Last Delay : 0.56s     Served     : 7         Late (>5s) : 4         │
│ Within 1s  : 94.54%    Within 3s  : 100.00%   Within 5s  : 100.00%   │
│- NODE RESOURCE USAGE ------------------------------------------------│
│ CPU (sys)  : 1.71%     Mem (Live) : 0.1G      GC Minor   : 2154      │
│ Mem (RSS)  : 0.3G      Mem (Heap) : 0.3G      GC Major   : 26        │
├─ CORE ───────────────────────────────────────────────────────────────┤
│ KES current/remaining             : 103 / 52                         │
│ KES expiration date               : 2023-02-07 12:00:00 UTC          │
│ Missed slot leader checks         : 0 (0.0000 %)                     │
│- BLOCK PRODUCTION ---------------------------------------------------│
│ Leader : 7             Adopted : 7            Invalid : 0            │
└──────────────────────────────────────────────────────────────────────┘
 TG Announcement/Support channel: t.me/guild_operators_official

 [esc/q] Quit | [i] Info | [p] Peer Analysis

```

Scheduled leader slots:
leader schedule for epoch 34

  No.	 slot/slotInEpoch		PDT time
-------------------------------------------------------------
  1	13048336/22984336		2022-11-17T16:32:16-08:00
  2	13048701/22984701		2022-11-17T16:38:21-08:00
  3	13050112/22986112		2022-11-17T17:01:52-08:00
  4	13075009/23011009		2022-11-17T23:56:49-08:00
  5	13095384/23031384		2022-11-18T05:36:24-08:00
  6	13100173/23036173		2022-11-18T06:56:13-08:00
  7	13100560/23036560		2022-11-18T07:02:40-08:00
  8	13122791/23058791		2022-11-18T13:13:11-08:00
  9	13126136/23062136		2022-11-18T14:08:56-08:00
  10	13140654/23076654		2022-11-18T18:10:54-08:00
  11	13153610/23089610		2022-11-18T21:46:50-08:00
  12	13163837/23099837		2022-11-19T00:37:17-08:00
  13	13174786/23110786		2022-11-19T03:39:46-08:00
  14	13190426/23126426		2022-11-19T08:00:26-08:00
  15	13207054/23143054		2022-11-19T12:37:34-08:00
  16	13210526/23146526		2022-11-19T13:35:26-08:00
  17	13215927/23151927		2022-11-19T15:05:27-08:00
  18	13216108/23152108		2022-11-19T15:08:28-08:00
  19	13225471/23161471		2022-11-19T17:44:31-08:00
  20	13229867/23165867		2022-11-19T18:57:47-08:00
  21	13230400/23166400		2022-11-19T19:06:40-08:00
  22	13234560/23170560		2022-11-19T20:16:00-08:00
  23	13240510/23176510		2022-11-19T21:55:10-08:00
  24	13252705/23188705		2022-11-20T01:18:25-08:00
  25	13273277/23209277		2022-11-20T07:01:17-08:00
  26	13283682/23219682		2022-11-20T09:54:42-08:00
  27	13288495/23224495		2022-11-20T11:14:55-08:00
  28	13289429/23225429		2022-11-20T11:30:29-08:00
  29	13300515/23236515		2022-11-20T14:35:15-08:00
  30	13312115/23248115		2022-11-20T17:48:35-08:00
  31	13322938/23258938		2022-11-20T20:48:58-08:00
  32	13330824/23266824		2022-11-20T23:00:24-08:00
  33	13336501/23272501		2022-11-21T00:35:01-08:00
  34	13352315/23288315		2022-11-21T04:58:35-08:00
  35	13356553/23292553		2022-11-21T06:09:13-08:00
  36	13356924/23292924		2022-11-21T06:15:24-08:00
  37	13367180/23303180		2022-11-21T09:06:20-08:00
  38	13372798/23308798		2022-11-21T10:39:58-08:00
  39	13376862/23312862		2022-11-21T11:47:42-08:00
  40	13377014/23313014		2022-11-21T11:50:14-08:00
  41	13378917/23314917		2022-11-21T12:21:57-08:00
  42	13400638/23336638		2022-11-21T18:23:58-08:00
  43	13410257/23346257		2022-11-21T21:04:17-08:00
  44	13421063/23357063		2022-11-22T00:04:23-08:00
  45	13422064/23358064		2022-11-22T00:21:04-08:00
  46	13422353/23358353		2022-11-22T00:25:53-08:00
  47	13424916/23360916		2022-11-22T01:08:36-08:00
  48	13429815/23365815		2022-11-22T02:30:15-08:00
  49	13436687/23372687		2022-11-22T04:24:47-08:00
  50	13437968/23373968		2022-11-22T04:46:08-08:00
  51	13454240/23390240		2022-11-22T09:17:20-08:00
  52	13458305/23394305		2022-11-22T10:25:05-08:00
  53	13460506/23396506		2022-11-22T11:01:46-08:00
  54	13461323/23397323		2022-11-22T11:15:23-08:00
  55	13461444/23397444		2022-11-22T11:17:24-08:00
  56	13464046/23400046		2022-11-22T12:00:46-08:00
  57	13465203/23401203		2022-11-22T12:20:03-08:00
  58	13469178/23405178		2022-11-22T13:26:18-08:00
Done!

**Comment by cexplorer** [comment]
are you on respinned network env?

**Comment by monkey-jsun** [comment]
Hmm what is preprod respin?  How do I know if I'm on the respinned network?

I believe I have done respin upgrade for preview network.  Not sure about preprod network.

**Comment by monkey-jsun** [comment]
I just turned it on and minted another block.  See log message below.

Nov 26 20:15:39 producer bash[2218]: [producer:cardano.node.Forge:Info:52] [2022-11-26 20:15:39.00 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("block",String "54f270196026e0d9d0fcbe506a1109ffcfe6d6c8c43e3438578c177ddc2b25f6"),("blockNo",Number 326382.0),("blockPrev",String "2b6cd9fcdff14bae6fa1a910c27c439ca76d4a0c68727d331a6d8ae396278b21"),("kind",String "TraceForgedBlock"),("slot",Number 1.3810539e7)]))]

**Comment by cexplorer** [comment]
We both are on different networks.

Your block 326382 is with different hash on our version: https://preprod.cexplorer.io/block/c014137ce57e3a33c1993e2272f3d0176ef5e6c90d2af9ced2973ba944056ab5 

Check your files there: https://book.world.dev.cardano.org/environments.html#pre-production-testnet

**Comment by AlleycatStudios** [comment]
I'm seeing the same issue... waiting for a new block to get it from the log.  I built my PreProd pool (ticker ALLEY) from scratch on 1.35.4 and used the config files from the link you referenced above.

**Comment by AlleycatStudios** [comment]
[alleycat:cardano.node.Forge:Info:58] [2022-11-28 15:04:31.00 UTC] fromList [("credentials",String "Cardano"),("val",Object (fromList [("block",String "3d5fbce0afef9a52ee7b171eb333831b4a1549948532e6dcadc4ba883631ac64"),("blockNo",Number 333834.0),("blockPrev",String "a9f0d3b073f8f7a602d422dda5dd41663a6bc8f1dc4b2d1af57199718be5b0a6"),("kind",String "TraceForgedBlock"),("slot",Number 1.3964671e7)]))]

**Comment by monkey-jsun** [comment]
> We both are on different networks.
> 
> Your block 326382 is with different hash on our version: https://preprod.cexplorer.io/block/c014137ce57e3a33c1993e2272f3d0176ef5e6c90d2af9ced2973ba944056ab5
> 
> Check your files there: https://book.world.dev.cardano.org/environments.html#pre-production-testnet

I checked my node and it is using the same files as the official link you provided.  Very very interesting and scary.  

Let me rebuild the database from scratch with v1.35.4

**Comment by monkey-jsun** [comment]
Note on the link you provided, it says preprod network never re-spin.  So the issue is not likely due to respinning network.

**Comment by monkey-jsun** [comment]
OK.  I see something changed on your site and now it shows all the blocks my pool has minted before.

Please close the issue.  But I'm curious what is done on your end.

**Comment by cardanians** [comment]
@monkey-jsun I mean both network respinned. But preprod was respinned not from epoch 0, but as continuation, only with different genesis hash = new network. This is, why you had pool on old and new network, but blocks were produced on this old network before and same pool.
