### ISSUE TITLE
pool margin is not updated and still shows old value

### ISSUE THREAD

**Issue by monkey-jsun** [cexplorer/cexplorer.io#34]
**Describe the bug**

The [MYADA pool](https://cexplorer.io/pool/pool1v675dnkxjfz9jgct00tskyyuvsjgqj50d27c6wz4a5zr6gj4s67) updated its meta data on 12/2, 2022, which is about 11 days ago.  This update reduced margin fee from 1% to 0%.  However, the web page still shows 1% as the pool margin fee.

**Comment by cexplorer** [comment]
I see all is ok now. Thanks for patience. Closing.
