### ISSUE TITLE
Preview Network Policy Lock time is Wrong

### ISSUE THREAD

**Issue by edridudi** [cexplorer/cexplorer.io#36]
[this policy id: 9a50f458ebffb4c3f9d6f9f3d45426b2de6cf2512254f4bfa3d8f410
](https://preview.cexplorer.io/policy/9a50f458ebffb4c3f9d6f9f3d45426b2de6cf2512254f4bfa3d8f410/timelock#data)

shows the wrong time for policy lock

**Comment by cexplorer** [comment]
thank you @edridudi 
fixed
