### ISSUE TITLE
Richlist page doesn't work anymore

### ISSUE THREAD

**Issue by Proxiweb** [cexplorer/cexplorer.io#37]
**Describe the bug**

When you set an amount and click on the  "Check my position"  button, it simply reload the page.

**To Reproduce**
1. Go to the richlist page
2. Set the amount
3. Click on 'Check my position'
5. Nothing happen

**Expected behavior**
I expect the rank to be displayed

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.01
 - Browser Firefox 107.0 and Chrome 108.0.5359.98

**Comment by cexplorer** [comment]
This issue is already fixed internally and will be live in 1-2 days. 

Thanks @Proxiweb !
