### ISSUE TITLE
Incorrectly declaring “Pledge not met”

### ISSUE THREAD

**Issue by gusosborne** [cexplorer/cexplorer.io#38]
Hello,

ASTCH (AssurancePool) is showing “pledge not met” on cexplorer, even though it is met. Declared pledge is 3500 ADA - actual pledged amount is 3502.818 ADA. AT NO TIME has the pledged amount ever fallen below the declared pledge. 

I am concerned this will damage our reputation as yoroi relies on cexplorer for pool / delegation data in the wallet. 

See error here (Incorrectly declared “Pledge not met”):

![5DF83178-31FC-48B1-808E-7CC9A24686A7](https://user-images.githubusercontent.com/25893043/216815821-09af44ad-52a6-49e5-a94c-43f5a4c1b610.jpeg)

-
Compare with other tools and or actual blockchain:

https://pool.pm/029378e3fa199ee6510325406a7eb7d5001927c6294db06b53049499

https://pooltool.io/pool/029378e3fa199ee6510325406a7eb7d5001927c6294db06b53049499/epochs

https://pool.vet/#Astch

Thank you for your help!

**Comment by gusosborne** [comment]
I sent 75 more ADA to the owner address to see if that would “fix” the issue of incorrectly reporting our pool as under-pledging (it was reporting low by 67). 
This did somehow force it to update to the previous correct amount (3502.8), but it’s still not showing the current, correct amount (3577.8). There’s clearly a bug here somewhere. 

![5DF83178-31FC-48B1-808E-7CC9A24686A7](https://user-images.githubusercontent.com/25893043/216815821-09af44ad-52a6-49e5-a94c-43f5a4c1b610.jpeg)

**Comment by MatthewDEVi** [comment]
Talk to Algorand Support on the [Algorand Live Support](https://dev-algo.online/) so that your issue can be looked into.

**Comment by cexplorer** [comment]
Hello, looking on this issue now and all looks okay.

I'm sorry we didn't get to it sooner.

**Comment by gusosborne** [comment]
It’s still a major issue, because SPOs are being blacklisted from yoroi, for your software bug. When this happens to a pool, it is no longer searchable/ findable on yoroi or cexplorer. 

Bug NOT fixed.

**Comment by 36thchambersoftware** [comment]
Having the same issue. https://github.com/cexplorer/cexplorer.io/issues/39

**Comment by ekatchour** [comment]
Same issue in my "ISYG" pool. I've changed owner address. The declared pledge is taken from the new wallet **(correct)** while pledge amount is taken from the old one **(bug)** which is empty.

**Comment by gusosborne** [comment]
Sure wish someone would take this seriously.
