### ISSUE TITLE
Allow multiple owners of a pool

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#4]
**Is your feature request related to a problem? Please describe.**
I operate a pool with a partner and I am not able to claim or manage my pool because they have already done so.

**Describe the solution you'd like**
I would like to be able to manage my pool listing along with my partner.

**Additional context**
I tried to claim my pool and received this message:
 This pool is actually claimed by someone else.
My partner is out of town and my listing has a problem - trying to claim the listing and figure out why the associated metadata is not showing up.
Important details like name and ticker are showing up "undefined".
https://cexplorer.io/pool/pool19n5ml38q5uedy8kgwwwtlsa3p9tmfcef0lfjp42k7j9d5mpgs2m

**Comment by frog357** [comment]
![image](https://user-images.githubusercontent.com/1760100/175833126-03032df9-ea78-446a-9477-d8bc50aec29b.png)
Everything is looking normal at adapools.
![image](https://user-images.githubusercontent.com/1760100/175833144-5f35e9e7-28bb-462d-bb44-35aa4c9d4e63.png)

**Comment by frog357** [comment]
Oh I just noticed the delegator count is off by 100 as well.

**Comment by cardanians** [comment]
implement multiple owners - we will consider implementation, thanks. but true is, there should be re-claim to another user and not only error message! - we will fix it ASAP; so you will be able reclaim pool under your account and check where is problem with metadata. maybe there is timeout issue, we have timeout about 2s and your file is loaded as average 1.5-2s?

about delegator count - we are excluding delegators without balance or less than 10 ADA for better precision "real delegators".

thanks!

**Comment by cardanians** [comment]
btw temporary multiowner solution : you can have in extended-metadata file both verification strings (yours and ver. string of your friend) and who needs manage pool, will only reclaim pool via web on click :]
