### ISSUE TITLE
Dead link to USDC (?)

### ISSUE THREAD

**Issue by isaac-infotrend** [cexplorer/cexplorer.io#44]
**Describe the bug**
Dead link to USDC (?)

https://cexplorer.io/token/asset1j6k6hw22ftpdguejflslvawvkl499j8qqj4se9 should work for USDC ?

**To Reproduce**
1. Go to https://bridge-explorer.milkomeda.com/cardano-mainnet/tokens
2. Click on '....' [this link](https://cexplorer.io/token/asset1j6k6hw22ftpdguejflslvawvkl499j8qqj4se9) for USDC
4. See rude minion 404 error

**Expected behavior**
Display of transactions list for USDC 

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome 
 - Version 112.0.5615.138

**Comment by cexplorer** [comment]
Hey, I tried to find USDC and url and all looks okay: 

https://cexplorer.io/asset/asset18f7zn35vthuh24ed4y6ucvmheur2wggcdfwj29
