### ISSUE TITLE
Cexplorer breaks when I search for this hash 5f13c86993a161185b9c2f43b91a3815fb4acafab3627a7f8a0a71e2c77ba0b8

### ISSUE THREAD

**Issue by Oswriv** [cexplorer/cexplorer.io#45]
Cexplorer breaks when I search for this hash 5f13c86993a161185b9c2f43b91a3815fb4acafab3627a7f8a0a71e2c77ba0b8

I sent 1.555555 NMKR + ada allocation from lace wallet to flint wallet. TX looks fine on Cardanoscan.
You can reach out via Discord if you want more details
Lace PO - Rivosw#1849

**Comment by cexplorer** [comment]
Hello @Oswriv fixed, thank you.
