### ISSUE TITLE
Error viewing transaction

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#47]
**Describe the bug**
500 error when viewing this page:
https://cexplorer.io/tx/2fa79b644e16b96017f66d3ce25509b8339a9d9f68751a9160f4b559c4d847bf

**To Reproduce**
1. Go to 'https://cexplorer.io/tx/2fa79b644e16b96017f66d3ce25509b8339a9d9f68751a9160f4b559c4d847bf'
2. See error

**Comment by cexplorer** [comment]
Thank you @frog357 
Issue fixed.
