### ISSUE TITLE
Adding pool certificate data to transactions which include it.

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#49]
**Is your feature request related to a problem? Please describe.**
Take a look at this transaction ID:
2e1db884fd1dfbf929fa110bdd574229b56013f333f691eaecaaa564f0f6bf48
When you view this with Cardanoscan you can see the associated pool certificate update. We changed the pool pledge here and I was unable to verify this with your website.

**Describe the solution you'd like**
I would like to see pool certificate information included with the transaction. 

**Describe alternatives you've considered**
Using this other website but that's not a realistic solution.

**Additional context**
:)

**Comment by cexplorer** [comment]
Thank you (again) @frog357 . This feature will be live in a few hours.
