### ISSUE TITLE
Transactions not showing reference scripts?

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#50]
**Describe the bug**

"The transaction Id referenced below is not showing any script or additional information."

**To Reproduce**

View this transaction:
8ab31bef39f6b3c11a8d5ada19aee6d492afb178bd77b12ebf954399414d3030

Now view this transaction on Cardanoscan.

**Comment by cexplorer** [comment]
As always, thank you @frog357 🥇 

Fixed + added tab reference inputs :) 

In a hour new version should be live.
