### ISSUE TITLE
Missing pool certificate / deregistration

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#51]
**Describe the bug**
A transaction was created to de-register a stake pool.
No information was provided regarding de-registration or certificates associated with this transaction as you find on other explorers.

**To Reproduce**
Query with this tx:
a12165b4c5ade674d3172bc53ec7c38a24b7126d40306fb0c60256c3ace51c13

**Expected behavior**
Show information regarding the deregistration scheduled for next epoch.

** Screenshots **
Something like this:
![image](https://github.com/cexplorer/cexplorer.io/assets/1760100/2d2199b1-1ea4-4f9c-9206-38e73b4ca26f)

**Comment by cexplorer** [comment]
Implemented, thanks @frog357
