### ISSUE TITLE
Metadata is dropped due to control character \r

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#52]
**Describe the bug**
I noticed a transaction in which you were not able to display the metadata.
42e229f133aa342b23371d17ad8e50e5da425941a8c01847cda0c53195d94f9c

**Expected behavior**
The metadata contained \r and I'm guessing you dropped it instead of encoding it.

**Screenshots**
![image](https://github.com/cexplorer/cexplorer.io/assets/1760100/e1f1782b-c1ef-40e8-8cad-ff198513872a)

**Comment by cexplorer** [comment]
in db-sync, tx meta table json is empty for this tx.
