### ISSUE TITLE
Active stake show on pool page is incorrect 

### ISSUE THREAD

**Issue by IndieStakeHub** [cexplorer/cexplorer.io#53]
**Describe the bug**
On my pool's page it shows the active stake as zero and pool performance data are wrong.

**To Reproduce**
Go to ['HERE'](https://cexplorer.io/pool/pool13g5ftmgqktfja04xwyd7yte8p0arelzyygndyfjr798vsx0cd6f)
Scroll down to 'Active Stake'
See amount listed as zero.

**Expected behavior**
The active stake should be shown as roughly 70K ada.
Pool performance show good data.

**Screenshots**
![image](https://github.com/cexplorer/cexplorer.io/assets/149335965/873efb52-ceb7-4473-aab6-d9abcd342d34)
![image](https://github.com/cexplorer/cexplorer.io/assets/149335965/4656906f-f829-4c32-be34-fb59dde81c98)

**Desktop (please complete the following information):**

OS: MacOS / Windows
Browser: Chrome, Safari, Edge
Version: All

**Comment by cexplorer** [comment]
Hello I see all is okay now.

Please note after epoch transition, active stake is visually not changed instantly, it takes a few hours due a ton of data which we need proceed on a lot of places.
