### ISSUE TITLE
Page displayed incorrectly for early (byron era?) blocks.

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#54]
**Describe the bug**

View this page:
https://cexplorer.io/block/3bd66578951b9ae032094b4307113d748436dec5c61af05dda1ef5e048e14dbf

![image](https://github.com/cexplorer/cexplorer.io/assets/1760100/c9e3225a-5558-481c-9640-10ee3df11701)

**Comment by cexplorer** [comment]
fixed, thanks!
