### ISSUE TITLE
Confusing stake information

### ISSUE THREAD

**Issue by cryptophonic** [cexplorer/cexplorer.io#57]
**Describe the bug**
On Sanchnet Cexplorer, pool is generating blocks but shows 0 stake and 0 delegates with confusing data for stake address owner.

**To Reproduce**
https://sancho.cexplorer.io/stake/stake_test1ur9uuse4lg5pj4rj8ph98uxr4d6dtnf9g7tazyqwfvdr8wqcvwd7n/analyze#data

**Expected behavior**
A graph that makes sense?

**Screenshots**
![image](https://github.com/cexplorer/cexplorer.io/assets/409166/8c492386-5982-4a9c-9aa4-915be164b0d5)

**Desktop (please complete the following information):**
Browser: Chrome (latest)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by cexplorer** [comment]
fixed thanks
