### ISSUE TITLE
Missing information from stake key lookup

### ISSUE THREAD

**Issue by frog357** [cexplorer/cexplorer.io#6]
**Describe the bug**
Look up these IOG/CF pool stake keys using CardanoScan vs. this website.
The problem is that you show nothing for transactions.

stake1uxs3crcc96zslc2xus3v9j2rgzwrxvt6pdgzu3we4whvjxgg4vfca
stake1u88nna5tmx6shmum40y9s3d2w6vgd8j5r3gs8n027nd4l3ctqwetj
stake1u98qeq562rulfrn7ndvqughnse26k0vr2le3rg6gz4d93sgh9vhrk
stake1uyy36x2h7rchrrpc06gsspntvvml2jnfjxne0e6yljdykdc8kdfen
stake1u97vdsdmrm4slrxjlltghy547xkv3hkeu8rtkrv4ke3sw9sxwmxal
stake1uxyrtpsfq2952x4zcyxgtj89eptf2jay4zjlk98zw0ynrjcyt3ymv
stake1u98tt35j56umllsn3nu0rdj9l00v7tv9zd0hramuh2sfnpq2a54vy
stake1uym6297nf5sq8rl26uak2u5rzevmeq8jvpxwzmzh25cl9wsel4e4t
stake1uxlr0yu4qjtuhx8f7wtfp2pqg2hc2x36tfxellzcyuy7yfg2c4mfj
stake1uxyllmwzckxd58ww3cmq76ckj3kn8n6g6l5fyj2lmd5egfgjj93ml
stake1uxkukp2hazjjcwspzcty4hh8a7tnkry30ufrs62rpe0s54qj7js8d
stake1u8s3rhujx895q38mye57axv8frr8v00hh7qg4q85hc6w8gs74yzrf
stake1u8knsucj4ql6gexxzprzgydycp39aq7wqec2fcpj7788n8qgdr4je
stake1uxkffxtd3ws9pz5t36humw5aarqv0phzt8w0nnur9fl5mqcr9slez
stake1u85sxxz4f6u69zg3hulpsqukk6l75ctsg8zgq2pggrhqacqzt2ns7
stake1u9mxda8vjc5htq3pw6yl8r2pcuyrg0uax4jup5jv29g2dlckuj0q9
stake1uyzku3s2wxu2ljhe6ykd9v9a8qkvn548nru7qnhjlj6s2ds8hz4mc
stake1u8fpv84fvlscglyyaamj58ngcu4v9effttm49zw05d2aslq6jnzpj

**Comment by cexplorer** [comment]
thank you @frog357

**Comment by cexplorer** [comment]
We have solved this issue by adding "Withdrawals" tab for every stake address.

Example:
https://cexplorer.io/stake/stake1uxyrtpsfq2952x4zcyxgtj89eptf2jay4zjlk98zw0ynrjcyt3ymv/withdrawal#data

and of course it is available then in TX detail:

https://cexplorer.io/tx/b2fe200ae710815fc0b877b6df9a6f936f8c907bd6ce3fec2622d3539d35434a#data
respective 
https://cexplorer.io/tx/b2fe200ae710815fc0b877b6df9a6f936f8c907bd6ce3fec2622d3539d35434a/withdrawal#data

Again, thank you
