### ISSUE TITLE
Price reported for MILK token by SundaeSwap exchange off

### ISSUE THREAD

**Issue by MuesliSwapTeam** [cexplorer/cexplorer.io#7]
**Describe the bug**
The price displayed for milk on sundaeswap is a millionth of the actual token price. Incorrect decimal handling?

**To Reproduce**
https://cexplorer.io/asset/asset1pwhywk7x54g739z3dqs245q62yu47vjh8gapjv/market

**Expected behavior**
Should be ~2 ADA

**Screenshots**
![image](https://user-images.githubusercontent.com/91151317/182362606-f7fa5908-85ba-4a0f-bb8c-b583ad355a07.png)

@SundaeSwap-finance

**Comment by cexplorer** [comment]
fixed thank you
